name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      working-directory: website/backend
      run: dotnet restore
    
    - name: Install dotnet ef
      working-directory: website/backend
      run: dotnet tool install --global dotnet-ef

    - name: Create Data folder
      working-directory: website/backend
      run: mkdir ./Infrastructure/Data

    - name: Database Migrations
      working-directory: website/backend
      run: dotnet ef migrations add init

    - name: Database Build
      working-directory: website/backend
      run: dotnet ef database update

    - name: Build
      working-directory: website/backend
      run: dotnet build --no-restore
    
    - name: Test
      working-directory: website/backend
      run: dotnet test --no-build --verbosity normal
