name: Frontend/Vue
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - working-directory: website/frontend
      - run: |
              npm ci
              npm run build
              npm run test:unit
              npm run lint
